<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>__NAMESPACE__.Infrastructure</RootNamespace>
    <AssemblyName>__NAME__.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\__NAME__.Domain\__NAME__.Domain.csproj" />
    <ProjectReference Include="..\__NAME__.Application\__NAME__.Application.csproj" />
  </ItemGroup>

</Project>
